# -*- coding: utf-8 -*-
"""
Created on Fri Mar 29 06:37:35 2019

@author: Andrej Leban
"""

import numpy as np
import pandas as pd
import scipy as sp

import matplotlib.pyplot as plt

import csv

# the data is generated by enabling the macro DUMPINTERMEDIATE in CMake

a = np.array(list(map(float, list(csv.reader(open("uniforms")))[0])))
plt.hist(a, bins=10, density=True)

plt.figure()
b = np.array(list(map(float, list(csv.reader(open("gaussians")))[0])))
b[b == -np.inf] = -np.finfo(float).max
b[b == np.inf] = np.finfo(float).max
bhist = b[b > -1000]
bhist = bhist[bhist < 1000]
plt.hist(bhist, bins=1000, density=True)
